---
title: "Learning More About AI"
---
  
# More Conceptual
## Including Applications of AI in Med Ed Assessment

**UNDER CONSTRUCTION**

# More Technical

For those who want to learn more about the technical aspects of GPTs, I highly recommend watching [3Blue1Brown's series on Neural Networks / Deep Learning](https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi). Some conceptual knowledge of matrix algebra will be helpful. Of particular interest will be [Chapter 5: But what is a GPT? Visual intro to transformers](https://youtu.be/wjZofJX0v4M?si=Ase-j746fiy-2KRK) and [Chapter 6: Attention in transformers, visually explained](https://youtu.be/eMlx5fFNoYc?si=ODqjp1C4L1KRfn-L). 

I also found [this blog post discussing LLM architecture to be accessible and informative.](https://www.lesswrong.com/posts/XGHf7EY3CK4KorBpw/understanding-llms-insights-from-mechanistic)

[DeepLearning.AI](https://learn.deeplearning.ai/) has a great selection of freely-available courses on select topics that are more appropriate for users more familiar with AI, such as:

- [Agentic AI](https://learn.deeplearning.ai/courses/agentic-ai/lesson/pu5xbv/welcome!)
- [Evaluating Agents](https://learn.deeplearning.ai/courses/evaluating-ai-agents/lesson/sqkza/introduction)
- [GenAI Workflow Orchestration](https://learn.deeplearning.ai/courses/orchestrating-workflows-for-genai-applications/lesson/tw64g/introduction)